[[main]]
identifier = "works"
name = "Работы"
url = "/works/"
weight = 1

[[main]]
identifier = "kurs"
name = "Курсовые"
url = "/kurs/"
weight = 2

[[main]]
identifier = "practices"
name = "Практики"
url = "/practices/"
weight = 3

[[main]]
identifier = "about"
name = "Обо мне"
url = "/about/"
weight = 4

[[main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5
[main.params]
icon = "search"

# [[main]]
# identifier = "archives"
# name = "Архив"
# url = "/archives/"
# weight = 6
# [main.params]
# icon = "archives"

# Социальные ссылки
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/danyakr"
[social.params]
icon = "brand-github"
